create table MOCK_WINE_DATA (
	wine_id INT,
	wine_name VARCHAR(64),
	country VARCHAR(64),
	region VARCHAR(64),
	winery VARCHAR(64),
	wine_description VARCHAR(8192),
	winegrape_variety VARCHAR(64),
	bottled_year INT,
	price DECIMAL(6,2),
	rating DECIMAL(2,1),
	food_pairing VARCHAR(64),
	serving_temperature DECIMAL(4,1),
	tasting_notes VARCHAR(64),
	wine_color VARCHAR(64),
	body VARCHAR(16),
	acidity VARCHAR(16),
	tannins VARCHAR(16),
	finish VARCHAR(16),
	oakiness VARCHAR(16),
	sweetness VARCHAR(16)
);

insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (1, 'Mystic Moon', 'Spain', 'Bordeaux', 'Whispering Pines Vineyard', 'Delicate and floral with a touch of honey', 'Chardonnay', 1835, 808.07, 1.7, 'pasta', 55.7, 'earthy', 'red', 'light', 'low', 'low', 'long', 'none', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (2, 'Velvet Elixir', 'Portugal', 'Piedmont', 'Grapevine Estates', 'Opulent and opulent with flavors of blackcurrant and chocolate', 'Merlot', 1870, 170.65, 2.2, 'pasta', 19.6, 'earthy', 'white', 'light', 'high', 'medium', 'long', 'subtle', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (3, 'Enchanted Vine', 'Australia', 'Rioja', 'Grapevine Estates', 'Juicy and vibrant with a burst of red berries', 'Chardonnay', 1955, 656.75, 3.1, 'steak', 73.7, 'spicy', 'rosé', 'full', 'high', 'high', 'short', 'none', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (4, 'Opulent Aura', 'Spain', 'Douro Valley', 'Whistling Winds Winery', 'Velvety and smooth with a hint of mocha', 'Merlot', 1714, 516.9, 1.7, 'sushi', 72.8, 'earthy', 'rosé', 'light', 'medium', 'medium', 'short', 'pronounced', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (5, 'Silken Serenade', 'Australia', 'Hunter Valley', 'Meadowbrook Winery', 'Crisp and dry with a zingy acidity', 'Cabernet Sauvignon', 1820, 942.08, 3.2, 'steak', 61.4, 'fruity', 'rosé', 'medium', 'medium', 'low', 'medium', 'none', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (6, 'Whispering Shadows', 'Australia', 'Hunter Valley', 'Vino Veritas', 'Juicy and ripe with a burst of ripe strawberries', 'Merlot', 1897, 886.39, 1.9, 'sushi', 81.2, 'fruity', 'rosé', 'light', 'medium', 'high', 'medium', 'none', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (7, 'Crimson Twilight', 'Spain', 'Napa Valley', 'Emerald Coast Winery', 'Rich and full-bodied with flavors of oak and vanilla', 'Grenache', 1789, 121.54, 2.4, 'pasta', 48.8, 'floral', 'white', 'full', 'medium', 'high', 'medium', 'pronounced', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (8, 'Golden Essence', 'Chile', 'Yarra Valley', 'Emerald Coast Winery', 'Elegant and refined with a subtle oak influence', 'Riesling', 1978, 224.0, 2.4, 'pizza', 80.8, 'oaky', 'sparkling', 'medium', 'low', 'low', 'long', 'subtle', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (9, 'Radiant Dream', 'France', 'Douro Valley', 'Whispering Pines Vineyard', 'Smooth and velvety with notes of dark berries', 'Cabernet Sauvignon', 1756, 367.42, 2.5, 'pizza', 9.9, 'fruity', 'red', 'medium', 'medium', 'low', 'long', 'subtle', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (10, 'Sapphire Symphony', 'Spain', 'Bordeaux', 'Wildflower Vineyards', 'Crisp and dry with a zingy acidity', 'Pinot Noir', 1954, 286.98, 2.1, 'nuts', 3.0, 'oaky', 'red', 'full', 'medium', 'low', 'medium', 'pronounced', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (11, 'Amber Enigma', 'United States', 'Barossa Valley', 'Vineyard Valley', 'Juicy and ripe with a burst of ripe strawberries', 'Syrah', 1741, 570.09, 1.2, 'steak', 44.5, 'fruity', 'rosé', 'medium', 'high', 'low', 'short', 'moderate', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (12, 'Emerald Enchantment', 'Chile', 'Alsace', 'Mountain View Vineyards', 'Savory and spicy with a touch of black pepper', 'Pinot Noir', 1702, 326.17, 4.3, 'pizza', 38.8, 'oaky', 'white', 'full', 'medium', 'medium', 'short', 'subtle', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (13, 'Pearlescent Spell', 'Italy', 'Alsace', 'Meadowbrook Winery', 'Delicate and floral with a touch of honey', 'Chardonnay', 1815, 609.92, 1.0, 'cheese', 47.3, 'floral', 'rosé', 'medium', 'high', 'high', 'short', 'moderate', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (14, 'Celestial Nectar', 'Portugal', 'Bordeaux', 'Silver Oak Cellars', 'Bright and fruity with a hint of spice', 'Sauvignon Blanc', 1838, 405.96, 4.6, 'steak', 61.5, 'earthy', 'white', 'medium', 'high', 'medium', 'short', 'moderate', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (15, 'Velvet Noir', 'France', 'Napa Valley', 'Wine Country Estates', 'Crisp and refreshing with a touch of minerality', 'Riesling', 1936, 615.7, 1.8, 'pasta', 12.1, 'earthy', 'white', 'light', 'low', 'low', 'medium', 'subtle', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (16, 'Scarlet Mirage', 'Argentina', 'Stellenbosch', 'Chateau de la Vine', 'Crisp and dry with a zingy acidity', 'Merlot', 1825, 675.17, 1.3, 'steak', 94.9, 'floral', 'red', 'medium', 'medium', 'low', 'short', 'moderate', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (17, 'Moonlit Symphony', 'United States', 'Champagne', 'Cedar Creek Winery', 'Elegant and balanced with a long', 'Chardonnay', 1958, 892.28, 3.3, 'pasta', 29.0, 'earthy', 'red', 'light', 'medium', 'low', 'long', 'pronounced', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (18, 'Gilded Harmony', 'South Africa', 'Bordeaux', 'Riverbend Winery', 'Vibrant and lively with tropical fruit aromas', 'Chardonnay', 1988, 83.13, 2.1, 'fruit', 2.0, 'floral', 'white', 'medium', 'medium', 'high', 'long', 'moderate', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (19, 'Ethereal Mist', 'Portugal', 'Willamette Valley', 'Misty Meadows Vineyard', 'Smooth and velvety with notes of dark berries', 'Malbec', 2022, 608.17, 4.0, 'cheese', 69.2, 'earthy', 'white', 'light', 'high', 'high', 'long', 'subtle', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (20, 'Cobalt Cascade', 'France', 'Hunter Valley', 'Wine Country Estates', 'Bright and fruity with a hint of spice', 'Sauvignon Blanc', 1941, 936.35, 3.9, 'pizza', 77.5, 'earthy', 'sparkling', 'full', 'low', 'high', 'medium', 'pronounced', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (21, 'Ruby Rapture', 'Spain', 'Santorini', 'Golden Vine Winery', 'Bright and fruity with a hint of spice', 'Zinfandel', 1743, 595.78, 2.3, 'steak', 58.0, 'oaky', 'sparkling', 'full', 'low', 'medium', 'medium', 'pronounced', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (22, 'Ivory Illusion', 'Italy', 'Marlborough', 'Oak Barrel Winery', 'Savory and spicy with a touch of black pepper', 'Sauvignon Blanc', 1994, 159.1, 2.4, 'pizza', 42.9, 'earthy', 'sparkling', 'medium', 'high', 'medium', 'short', 'moderate', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (23, 'Midnight Mirage', 'Chile', 'Douro Valley', 'Cedar Creek Winery', 'Aromatic with hints of citrus', 'Riesling', 1782, 614.63, 3.2, 'nuts', 56.3, 'fruity', 'sparkling', 'light', 'medium', 'low', 'long', 'none', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (24, 'Crimson Cascade', 'Germany', 'Stellenbosch', 'Moonlight Vineyards', 'Bold and robust with intense dark fruit flavors', 'Zinfandel', 1963, 240.22, 4.2, 'steak', 97.4, 'earthy', 'sparkling', 'medium', 'medium', 'low', 'long', 'none', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (25, 'Amethyst Ambrosia', 'Argentina', 'Rioja', 'Misty Meadows Vineyard', 'Silky and seductive with layers of black cherry and plum', 'Cabernet Sauvignon', 1860, 904.08, 1.0, 'salad', 86.1, 'oaky', 'red', 'light', 'medium', 'medium', 'short', 'pronounced', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (26, 'Silken Spell', 'Spain', 'Champagne', 'Autumn Leaves Winery', 'Luscious and creamy with a touch of caramel', 'Grenache', 1974, 745.96, 3.1, 'seafood', 28.4, 'oaky', 'rosé', 'full', 'high', 'medium', 'short', 'moderate', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (27, 'Opulent Obsidian', 'Chile', 'Tuscany', 'Crimson Creek Winery', 'Elegant and refined with a subtle oak influence', 'Pinot Noir', 1828, 300.5, 2.9, 'chocolate', 62.0, 'oaky', 'white', 'full', 'medium', 'high', 'long', 'subtle', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (28, 'Whispering Zephyr', 'Argentina', 'Mendoza', 'Oak Barrel Winery', 'Juicy and vibrant with a burst of red berries', 'Pinot Noir', 1763, 643.42, 3.1, 'steak', 21.2, 'floral', 'rosé', 'light', 'medium', 'low', 'short', 'none', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (29, 'Luminous Lullaby', 'Portugal', 'Santorini', 'Chateau de la Vine', 'Silky and seductive with layers of black cherry and plum', 'Merlot', 1893, 280.62, 3.3, 'seafood', 83.5, 'floral', 'rosé', 'light', 'low', 'high', 'long', 'pronounced', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (30, 'Velvet Tempest', 'Italy', 'Barossa Valley', 'Moonlight Vineyards', 'Opulent and opulent with flavors of blackcurrant and chocolate', 'Riesling', 1922, 547.72, 1.0, 'pizza', 12.7, 'spicy', 'red', 'medium', 'medium', 'high', 'short', 'moderate', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (31, 'Mystic Moon', 'South Africa', 'Tuscany', 'Wildflower Vineyards', 'Crisp and dry with a zingy acidity', 'Sauvignon Blanc', 1841, 955.31, 1.4, 'seafood', 96.3, 'fruity', 'red', 'light', 'medium', 'high', 'long', 'none', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (32, 'Velvet Elixir', 'Argentina', 'Bordeaux', 'Rustic Ridge Winery', 'Fresh and zesty with citrus and floral notes', 'Riesling', 1949, 715.11, 2.0, 'cheese', 65.6, 'floral', 'white', 'light', 'medium', 'low', 'long', 'pronounced', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (33, 'Enchanted Vine', 'Australia', 'Willamette Valley', 'Riverbend Winery', 'Vibrant and lively with tropical fruit aromas', 'Riesling', 1701, 843.52, 1.4, 'cheese', 4.9, 'earthy', 'red', 'light', 'low', 'medium', 'long', 'moderate', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (34, 'Opulent Aura', 'Chile', 'Rioja', 'Whispering Pines Vineyard', 'Delicate and floral with a touch of honey', 'Chardonnay', 1949, 384.47, 2.6, 'sushi', 93.1, 'earthy', 'red', 'medium', 'medium', 'medium', 'long', 'pronounced', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (35, 'Silken Serenade', 'Germany', 'Stellenbosch', 'Mountain View Vineyards', 'Savory and spicy with a touch of black pepper', 'Malbec', 1931, 911.54, 1.7, 'pasta', 6.8, 'floral', 'red', 'light', 'high', 'low', 'long', 'pronounced', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (36, 'Whispering Shadows', 'South Africa', 'Burgundy', 'Whistling Winds Winery', 'Vibrant and lively with tropical fruit aromas', 'Chardonnay', 1891, 175.01, 4.8, 'pizza', 18.5, 'floral', 'white', 'full', 'medium', 'medium', 'long', 'subtle', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (37, 'Crimson Twilight', 'Italy', 'Tuscany', 'Golden Vine Winery', 'Opulent and opulent with flavors of blackcurrant and chocolate', 'Cabernet Sauvignon', 1871, 102.72, 2.0, 'pasta', 22.0, 'oaky', 'sparkling', 'light', 'medium', 'low', 'short', 'subtle', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (38, 'Golden Essence', 'South Africa', 'Central Otago', 'Vintage Cellars', 'Crisp and dry with a zingy acidity', 'Malbec', 1701, 265.4, 2.7, 'nuts', 59.9, 'oaky', 'white', 'light', 'low', 'high', 'short', 'moderate', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (39, 'Radiant Dream', 'United States', 'Burgundy', 'Rustic Ridge Winery', 'Complex and earthy with hints of tobacco and leather', 'Malbec', 2021, 196.16, 2.8, 'seafood', 82.7, 'floral', 'white', 'full', 'low', 'low', 'short', 'none', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (40, 'Sapphire Symphony', 'Italy', 'Santorini', 'Wildflower Vineyards', 'Bold and robust with intense dark fruit flavors', 'Zinfandel', 1898, 972.47, 3.3, 'pizza', 60.1, 'floral', 'white', 'full', 'medium', 'low', 'long', 'pronounced', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (41, 'Amber Enigma', 'Germany', 'Rioja', 'Riverbend Winery', 'lingering finish', 'Chardonnay', 1759, 732.23, 3.0, 'salad', 0.0, 'fruity', 'red', 'full', 'high', 'high', 'long', 'moderate', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (42, 'Emerald Enchantment', 'South Africa', 'Stellenbosch', 'Oak Barrel Winery', 'Crisp and refreshing with a touch of minerality', 'Merlot', 1899, 514.74, 1.3, 'seafood', 29.2, 'fruity', 'white', 'light', 'medium', 'high', 'long', 'pronounced', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (43, 'Pearlescent Spell', 'Portugal', 'Douro Valley', 'Meadowbrook Winery', 'Vibrant and lively with tropical fruit aromas', 'Grenache', 1977, 921.55, 4.8, 'nuts', 90.2, 'floral', 'rosé', 'light', 'high', 'high', 'long', 'subtle', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (44, 'Celestial Nectar', 'South Africa', 'Mendoza', 'Riverbend Winery', 'Vibrant and lively with tropical fruit aromas', 'Sauvignon Blanc', 1875, 793.98, 3.8, 'salad', 60.6, 'oaky', 'rosé', 'light', 'low', 'high', 'short', 'moderate', 'sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (45, 'Velvet Noir', 'Chile', 'Central Otago', 'Mountain View Vineyards', 'Vibrant and lively with tropical fruit aromas', 'Merlot', 2005, 387.71, 3.8, 'seafood', 61.5, 'floral', 'white', 'medium', 'low', 'medium', 'long', 'subtle', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (46, 'Scarlet Mirage', 'France', 'Burgundy', 'Hidden Valley Cellars', 'Fresh and zesty with citrus and floral notes', 'Merlot', 1998, 856.98, 3.1, 'salad', 15.8, 'earthy', 'sparkling', 'medium', 'medium', 'low', 'short', 'none', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (47, 'Moonlit Symphony', 'United States', 'Burgundy', 'Cedar Creek Winery', 'Elegant and refined with a subtle oak influence', 'Grenache', 1901, 945.8, 3.3, 'nuts', 38.3, 'earthy', 'red', 'light', 'low', 'high', 'long', 'none', 'off-dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (48, 'Gilded Harmony', 'Spain', 'Central Otago', 'Vino Veritas', 'Bold and robust with intense dark fruit flavors', 'Pinot Noir', 1907, 503.83, 2.3, 'seafood', 3.3, 'oaky', 'sparkling', 'full', 'low', 'medium', 'medium', 'none', 'dry');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (49, 'Ethereal Mist', 'Chile', 'Marlborough', 'Vineyard Valley', 'Silky and seductive with layers of black cherry and plum', 'Zinfandel', 1932, 829.73, 3.7, 'nuts', 98.5, 'oaky', 'sparkling', 'medium', 'medium', 'low', 'long', 'subtle', 'semi-sweet');
insert into MOCK_WINE_DATA (wine_id, wine_name, country, region, winery, wine_description, winegrape_variety, bottled_year, price, rating, food_pairing, serving_temperature, tasting_notes, wine_color, body, acidity, tannins, finish, oakiness, sweetness) values (50, 'Cobalt Cascade', 'Australia', 'Rheingau', 'Sunny Slope Winery', 'Crisp and dry with a zingy acidity', 'Grenache', 2003, 154.69, 4.6, 'steak', 92.9, 'spicy', 'sparkling', 'full', 'low', 'medium', 'medium', 'moderate', 'sweet');
